apiVersion: v1 
kind: Pod 
metadata: 
  name: ebs-pod 
spec: 
  containers: 
  - name: app 
    image: nginx 
    volumeMounts: 
    - mountPath: "/usr/share/nginx/html" 
      name: ebs-storage 
  volumes: 
  - name: ebs-storage 
    persistentVolumeClaim: 
      claimName: ebs-pvc