apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: falco
  template:
    metadata:
      labels:
        app: falco
    spec:
      containers:
      - name: falco
        image: falcosecurity/falco:latest
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /host/proc
          name: proc
          readOnly: true
        - mountPath: /host/boot
          name: boot
          readOnly: true
        - mountPath: /host/lib/modules
          name: libmodules
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: dockersock
        - mountPath: /usr
          name: usr
          readOnly: true
      volumes:
      - hostPath:
          path: /proc
        name: proc
      - hostPath:
          path: /boot
        name: boot
      - hostPath:
          path: /lib/modules
        name: libmodules
      - hostPath:
          path: /var/run/docker.sock
        name: dockersock
      - hostPath:
          path: /usr
        name: usr
